---
ID: "c2e7d5cc-eaf7-475a-acc1-7686b82e7a95"
Parent: "af368d9a-7c88-56ae-8a26-7deddd1a5bae"
Template: "6d1cd897-1936-4a3a-a511-289a94c2a7b1"
Path: "/sitecore/content/Tenant/TestXmCloud/Dictionary/Products-Detail-Price"
SharedFields:
- ID: "580c75a8-c01a-4580-83cb-987776ceb3af"
  Hint: Key
  Value: "Products-Detail-Price"
Languages:
- Language: en
  Fields:
  - ID: "2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e"
    Hint: Phrase
    Value: Price
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210506T162842Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "64184631-8404-4f19-92d0-7353200e4786"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210506T162848Z
