---
ID: "7a1d5466-3e17-4809-9776-9d1dca7bec14"
Parent: "6f4ea3bc-1dda-43b3-af1b-af4a5d31a000"
Template: "c14bf746-030f-4e59-8594-395f6d299e61"
Path: /sitecore/content/Tenant/Multi/Settings/Shared Sites Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220411T073834Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "464bec7b-679c-4872-b7a3-ecca69726734"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220411T073834Z
