---
ID: "81fa918c-3d56-43e9-8338-5cd551124270"
Parent: "739cbdb4-eb48-4af5-96ab-b11f9bc2a589"
Template: "739cbdb4-eb48-4af5-96ab-b11f9bc2a589"
Path: /sitecore/templates/Project/TestXmCloud/Folder Types/Page Component Folder/__Standard Values
SharedFields:
- ID: "a791f095-2521-4b4d-bef9-21dda221f608"
  Hint: __Style
  Value: "font-size: 90%; font-style: italic;"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210504T184026Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "36a12056-ba27-4fde-9411-82182ff05f23"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210504T184048Z
