---
ID: "7fa8465f-141b-42b6-b3a3-297fe9d0cfb9"
Parent: "8e82ebad-c544-461c-93ba-29fd595eb5d6"
Template: "8e82ebad-c544-461c-93ba-29fd595eb5d6"
Path: /sitecore/templates/Feature/BasicContent/Content Block/__Standard Values
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210504T174945Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c925bd6c-0657-45f8-be27-7fd25351ee87"
    - ID: "ae347872-b492-43f5-affd-0f5adc59bdd0"
      Hint: Heading
      Value: 
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210512T184742Z
